name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Setup dependencies
        run: pip install tikzplotlib
      - name: Run tests
        run: julia --project=. --check-bounds=yes -e 'using Pkg; Pkg.test(coverage=true);'
      - name: Upload coverage
        run: julia -e "using Pkg; Pkg.add(\"Coverage\"); using Coverage; Codecov.submit(Codecov.process_folder())"
